// Outline
//
// # Further thoughts on politics
// ## Insights
// - It's becoming increasingly clear that politics can't be properly
//   modeled without having different population components, such as
//   priests, landowners, clients, and so on, as well as gender.
// - When on a "toward statehood" track, societies will often have
//   "setbacks" where some development of state power is checked or
//   reversed, possibly by disruptive violent or nonviolent events.
// - There should be in general various possibilities of types of
//   societies to develop to, with some level of choice by their
//   members, and not all of them equivalent to "states" as conventionally
//   defined.
//
// ## "Classes"
// - General notes:
//   - Classes below are mutually exclusive.
//   - Many classes can be property owners, which also allows them to
//     gain debtor clients. 
// - Clan member: a "regular person" in the original clan system.
//   Clans are initially considered to be autonomous, either as
//   individuals, or as clans, with individuals having many obligations
//   to their clan.
// - Tribal chief: heads of clans, phrateries, and tribes. Initially
//   they lead largely by persuasion, but many also have secret societies,
//   taboos, or judicial roles to enhance their power. Persuasive ability 
//   depends on culture and recent events.
// - Notables: tribal chiefs, usually of larger units, who have more
//   capital and influence than usual. Initially they are otherwise not 
//   that different from tribal chiefs. They can introduce a new ideological
//   element saying that they are a distinct class, more fit to rule,
//   further enhancing their power. They can also have a retinue, which
//   can be an elite military force or enhance power by force. They can
//   also install taxation ideologies.
// - Priests: religious specialists in temples, usually converted from
//   chiefs or notables. They may enhance their power through elaborated
//   rituals, secret societies, taboos, or judicial roles as well. They
//   can install religious mandates as ideologies, including requirements
//   to donate to temples.
// - Bonded workers: debt slaves or other types of workers who are
//   bound to a property owner. They will still have influence, but it's
//   *through* the property owner, who thus takes a share of it. These
//   can also be acquired via raiding.
// - Military clients: people with a primarily military organization who
//   are clients of a notable or priest. They must be paid more than basic
//   workers. They have more military skills, morale, and can spend much
//   more time on military action.
// - Merchants: people who carry out trade, of a variety of wealth levels,
//   most of them not particularly high. We might need to split out an
//   elite at some point but perhaps not yet. Their influence presumably
//   depends on the importance of trade to other classes.
// - Artisan clients: people who produce specialty goods such as high-quality
//   pottery, tools, and clothing. Like military clients, they must be paid
//   extra.
// Later:
// - Military elites ("generals")
//   - "Commander in chief" ideology can be installed
// - Merchant elites
// - Rulers of various kinds
//
// ## Developments in southern Mesopotamia 5000-3500 BC
// - At first, it seems there was a tribal society, with some chiefs and
//   artisans who had bigger houses, but no sign of elite goods or fancy
//   burials.
//   - The extra wealth may have been generated by advantageous farming,
//     but it's also possible there is some donation system to the chiefs.
// - Some time after 

//
// Original stuff:
//
// Classically there are stages of political development like this:
// - Egalitarian bands
//   - typically immediate-return hunter-gatherers
//   - status differences but not formalized
//   - leadership by assent of each and all
//   - traditional norms
// - Achievement-based ("big man") societies
//   - typically early hortculturalists
//   - formal degrees of status can be achieved as an adult
//   - leadership by assent of each and all, but emerging client relationships
//   - traditional norms, but perhaps shaped more by big-man choices
// - Ranked societies
//   - typically agriculturalists
//   - families are ranked and status depends heavily on birth
//   - some degree of coercion
//   - traditional norms, but some ability of chiefs and elites to alter them
// - Stratified societies
//   - typically agriculturalists with some degree of urbanization
//   - formal classes and stations
//   - coercion and exploitation generally available
//   - traditional norms still apply but often overridden by authorities
//
// However, our goal is not to have a schematic progression, but rather to
// model the transitions between these kinds of societies, and the causes
// and effects in all power sources.
//
// Starting point: 5000 BC, ranked societies. Although it would be interesting
// to model developments in simpler stages, and at some point we may, not that
// much is happening just yet, so it will be more interesting to start with
// somewhat more complex societies.
//
// Initial model for ranked societies:
//
// - Think about it in terms of 
//   (a) political actions and decisions available
//   (b) effects on other power sources and itself
//   (c) causes of development of additional *single features* of stratified societies
//       and the effects of those features
//
// - Political actions and decisions available
// - Effects on other power sources and itself
//   - Production: 
//     - Coordination bonus to local tile production for all goods
//       - Represents appropriate subsidy, trade regulation, dispute resolution
//     * Ability to create larger irrigation works
//   - Trade: 
//     - Coordination bonus to local trade
//     * Ability to coordinate long-distance trade, including with off-map trade points
//   - Consumption: Utility bonus for redistribution
//   - Technology: Bonuses due to scale, coordination, and subsidy/insurance
//     - Maybe ability to increase technological development in a particular area
//   - Religion: Bonus ability to claim labor
//   - Military:
//     - Coordination bonus to military actions, but relatively minor at this point
//     * Ability to build fortifications
//     * Suppression of internal raiding
//     * Wars with specific goals: territorial claims, tribute, trade routes
//   - Diplomacy:
//     * Peace agreements
//     * Alliances; perhaps start out with certain traditional alliances in effect
//     * Trade agreements
// - Additional features that can develop and their causes and effects
//   - First, we need to think through what additional developments can occur
//     in each area to make the politics more "state-like"
//     - Military:
//       * Professional armies
//       - State-provided equipment
//       - Meritocratic command
//       - Strategic planning and advisors
//     - Economy:
//       * Labor specialization
//       * Currency
//       * Long-distance trade
//       - Trade regulation and jurisprudence
//       - Taxation and corvee
//       - Luxury goods
//       - Marketplaces
//       - Social stratification determines consumption
//     - Culture:
//       - Religious specialization and hierarchy
//       * More elaborate temples and monuments
//       - Political endorsement of or affiliation with religion
//       - Cultural conversion and/or syncretism
//     - Technology:
//       - Advanced tools and equipment
//       * Writing, history, written records, laws, and lineages
//       - Subsidized education and research
//     - Diplomacy:
//       - Formal diplomatic missions and protocols
//       * Treaties and alliances with other states
//       - Vassalage relationships
//     - Politics:
//       - Decoupling of rulership from family structure
//       * Variability of power sources
//       - Bureaucracy
//       - Written laws